new-gggg

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,8 +4,7 @@ on:
   push:
     tags:
       - "prod-*"
-    branches:
-      - new-feature
+  
 
 jobs:
   build:
@@ -38,6 +37,19 @@ jobs:
 
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # Fetch all history to check the branch
+
+      - name: Verify tag is from main branch
+        run: |
+          TAG_NAME=${{ github.ref_name }}  # e.g., v1.0.0
+          BRANCH=$(git branch -r --contains tags/$TAG_NAME | grep -E 'origin/new-feature$')
+          if [ -z "$BRANCH" ]; then
+              echo "Error: Tag $TAG_NAME is not from the new-feature branch!"
+              exit 1
+          else
+              echo "Tag $TAG_NAME is confirmed to be from new-feature branch."
+          fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
