updates

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     # if: github.ref_name == 'new-feature'
+    # if: contains(github.ref_name , 'prod')
 
     steps:
       - name: Print GitHub Context Variables
@@ -28,7 +29,24 @@ jobs:
         with:
           fetch-depth: 0 # Fetch all history to check the branch
 
-      
+      - name: Print GitHub Context Variables
+        run: |
+          echo "github.ref: $GITHUB_REF"
+          echo "github.ref_name: $GITHUB_REF_NAME"
+          echo "github.base_ref: $GITHUB_BASE_REF"
+          echo "github.event_name: $GITHUB_EVENT_NAME"
+          echo "github.head_ref: $GITHUB_HEAD_REF"
+          echo "github.event.base_ref: $GITHUB_EVENT_BASE_REF"
+      - name: Verify tag is from main branch
+        run: |
+          TAG_NAME=${{ github.ref_name }}  # e.g., v1.0.0
+          BRANCH=$(git branch -r --contains tags/$TAG_NAME | grep -E 'origin/new-feature$')
+          if [ -z "$BRANCH" ]; then
+              echo "Error: Tag $TAG_NAME is not from the new-feature branch!"
+              exit 1
+          else
+              echo "Tag $TAG_NAME is confirmed to be from new-feature branch."
+          fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
